### ISSUE TITLE
does not work when running love from different directory

### ISSUE THREAD

**Issue by premek** [BearishMushroom/goif#3]
After this commit it works for me on linux when goif is in a subfolder ee3d1cff449e383c11be5f7d82812e9bacffd25d

But it still does not work when I need to run `love` from different directory:

```
premek@nuc:~/prog/forest$ ls src/main.lua 
src/main.lua
premek@nuc:~/prog/forest$ ls src/lib/goif/goif.lua 
src/lib/goif/goif.lua
premek@nuc:~/prog/forest$ love src/
SourceBaseDirectory /home/premek/prog/forest
WorkingDirectory    /home/premek/prog/forest
path    ./lib/goif/
Error: lib/goif/goif.lua:49: attempt to call local 'lib' (a nil value)
stack traceback:
    lib/goif/goif.lua:49: in main chunk
    [C]: in function 'require'
    main.lua:6: in main chunk
    [C]: in function 'require'
    [string "boot.lua"]:428: in function <[string "boot.lua"]:274>
    [C]: in function 'xpcall'
```

This works:

```
premek@nuc:~/prog/forest$ cd src/
premek@nuc:~/prog/forest/src$ love .
SourceBaseDirectory /home/premek/prog/forest
WorkingDirectory    /home/premek/prog/forest/src
path    ./lib/goif/
```

I tried to fix it with SourceBaseDirectory & WorkingDirectory and I printed their values but it's not helping. I don't even know if their output is correct. Looks weird to me.

**Comment by premek** [comment]
Also asked here https://bitbucket.org/rude/love/issues/1095/filesystemgetsourcebasedirectory-behavior

**Comment by BearishMushroom** [comment]
Could you try the fix in branch "folder_path" commit c5eb23c60f6924bf35a8e36417c7235287090079 ? It works fine for me on Windows and 64-bit Mint.

**Comment by premek** [comment]
Tested and it works. Thanks a lot!

**Comment by BearishMushroom** [comment]
Closing issue, merged the branch.

**Comment by premek** [comment]
FYI this comment mentions also undocumented love.filesystem.getSource() function which is probably what we needed

https://bitbucket.org/rude/love/issues/1095/filesystemgetsourcebasedirectory-behavior#comment-30672961
